version: "2"

run:
  timeout: 5m
  go: '1.23'
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    # Default enabled linters
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Security
    - gosec
    - bodyclose
    
    # Style and formatting
    - whitespace
    - misspell
    
    # Code quality
    - gocritic
    - revive
    - cyclop
    - funlen
    
    # Error handling
    - errorlint
    - errname
    
    # Best practices
    - goconst
    - prealloc
    - unconvert
    
    # Additional useful linters
    - gocyclo
    - dupl
    - nakedret

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow

    staticcheck:
      checks: ["all"]

    gosec:
      severity: medium
      confidence: medium

    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - paramTypeCombine
        - unnamedResult

    revive:
      rules:
        - name: exported
        - name: package-comments
        - name: var-naming
        - name: error-return
        - name: error-naming

    funlen:
      lines: 100
      statements: 50

    cyclop:
      max-complexity: 15

    gocyclo:
      min-complexity: 15

    dupl:
      threshold: 100

    nakedret:
      max-func-lines: 30

    misspell:
      locale: US

    goconst:
      min-len: 3
      min-occurrences: 3

  exclusions:
    rules:
      # Exclude some linters from running on test files
      - path: _test\.go
        linters:
          - gosec
          - funlen
          - goconst
          - dupl
          - gocyclo

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

