name: Helm Chart Release

on:
  push:
    branches: [ main ]
    paths: [ 'charts/**' ]
  release:
    types: [published]
  workflow_dispatch:

env:
  HELM_VERSION: 'v3.14.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: ${{ env.HELM_VERSION }}

    - name: Set up chart version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          VERSION="${{ github.event.release.tag_name }}"
          VERSION=${VERSION#v}  # Remove 'v' prefix if present
        else
          # Use current chart version for regular pushes
          VERSION=$(grep '^version:' ./charts/eks-pod-identity-webhook/Chart.yaml | cut -d' ' -f2)
          if [[ -z "$VERSION" ]]; then
            VERSION="0.1.0"
          fi
        fi
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Chart version: ${VERSION}"

    - name: Update chart version
      run: |
        sed -i "s/^version:.*/version: ${{ steps.version.outputs.VERSION }}/" ./charts/eks-pod-identity-webhook/Chart.yaml
        
    - name: Package Helm chart
      run: |
        mkdir -p .helm-releases
        helm package ./charts/eks-pod-identity-webhook --destination .helm-releases

    - name: Checkout gh-pages branch  
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup gh-pages directory
      run: |
        # Create gh-pages directory if it doesn't exist
        if [ ! -d "gh-pages" ]; then
          mkdir gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout -b gh-pages
        fi
        
    - name: Copy chart and generate index
      run: |
        # Copy the packaged chart to gh-pages directory
        cp .helm-releases/*.tgz gh-pages/
        cd gh-pages
        
        # Generate/update index.yaml
        if [ -f index.yaml ]; then
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }} --merge index.yaml
        else
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        fi
        
        # Create a simple index.html for the repository
        cat > index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>EKS Pod Identity Webhook Helm Repository</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 2rem; }
                .container { max-width: 800px; margin: 0 auto; }
                pre { background: #f5f5f5; padding: 1rem; border-radius: 4px; }
                .chart { background: #fff; border: 1px solid #ddd; padding: 1rem; margin: 1rem 0; border-radius: 4px; }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>EKS Pod Identity Webhook Helm Repository</h1>
                <p>This is a Helm chart repository for the EKS Pod Identity Webhook.</p>
                
                <h2>Usage</h2>
                <pre>helm repo add mondu-ai https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
        helm repo update
        helm install eks-pod-identity-webhook mondu-ai/eks-pod-identity-webhook</pre>
                
                <h2>Available Charts</h2>
                <div class="chart">
                    <h3>eks-pod-identity-webhook</h3>
                    <p>Kubernetes mutating admission webhook for AWS IAM role assumption in non-EKS clusters</p>
                    <p><strong>Repository:</strong> <a href="https://github.com/${{ github.repository }}">https://github.com/${{ github.repository }}</a></p>
                </div>
            </div>
        </body>
        </html>
        EOF

    - name: Commit and push to gh-pages
      run: |
        cd gh-pages
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Release helm chart version ${{ steps.version.outputs.VERSION }}"
          git push origin gh-pages
        fi

    - name: Summary
      run: |
        echo "## 🚀 Helm Chart Released!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Chart Version:** ${{ steps.version.outputs.VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Repository URL:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Installation Commands:" >> $GITHUB_STEP_SUMMARY
        echo '```bash' >> $GITHUB_STEP_SUMMARY
        echo "helm repo add mondu-ai https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
        echo "helm repo update" >> $GITHUB_STEP_SUMMARY
        echo "helm install eks-pod-identity-webhook mondu-ai/eks-pod-identity-webhook" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY 
